Parallel multiplication
Azernem/Semester-3 pull request #1
Opened 2024-09-15 23:24 UTC by Azernem

2024-11-16 21:33 UTC, yurii-litvinov requested changes
По существу всё так, но как-то очень коряво

2024-11-16 21:33 UTC, yurii-litvinov commented on ParallelMultiply/ParallelMultiply/MatrixOperation.cs
> +            var threads = new Thread[Environment.ProcessorCount];
Если в матрице меньше строк, чем доступно процессоров, будут созданы лишние потоки, тут стоит немного точнее определять потребное количество.

2024-11-16 21:33 UTC, yurii-litvinov commented on ParallelMultiply/ParallelMultiply/MatrixOperation.cs
> +                    for (var n = locall*blockSize; n < (locall + 1) * blockSize; n++)
Тут пробелов не хватает

2024-11-16 21:33 UTC, yurii-litvinov commented on ParallelMultiply/ParallelMultiply/Program.cs
> +using System.Diagnostics;
А тут предупреждение StyleCop надо заглушить.

2024-11-16 21:33 UTC, yurii-litvinov commented on ParallelMultiply/ParallelMultiply/Program.cs
> +var Sizes = new List<int>();
Переменные с заглавной в C# не именуются

2024-11-16 21:33 UTC, yurii-litvinov commented on SimpleFTP/.vscode/settings.json
> +{}
SimpleFTP в этом пуллреквесте ни к чему вроде :)

2024-11-30 21:15 UTC, yurii-litvinov requested changes
Мало что поменялось.

2024-11-30 21:15 UTC, yurii-litvinov commented on ParallelMultiply/ParallelMultiply/Exceptions/AnotherTypeException.cs
> +    public AnotherTypeException(string message): base(message)
StyleCop по делу ругается, base на следующей строке самое место

2024-11-30 21:15 UTC, yurii-litvinov commented on ParallelMultiply/ParallelMultiply/Exceptions/EmptyFileException.cs
> +    /// <param name="message">message.</param>
Но ведь у него нет параметра

2024-11-30 21:15 UTC, yurii-litvinov commented on ParallelMultiply/ParallelMultiply/FileMatrix.cs
> +        var random = new Random();
Random лучше сделать полем, а то и статическим полем. Его больше одного никогда не нужно, создавать его на каждом вызове GenerateMatrix — впустую мучить сборщик мусора

2024-11-30 21:15 UTC, yurii-litvinov commented on ParallelMultiply/ParallelMultiply/FileMatrix.cs
> +    public int[,] matrix;
public-поле, не исправлено, всё ещё -2 балла за задачу

2024-11-30 21:15 UTC, yurii-litvinov commented on ParallelMultiply/ParallelMultiply/Exceptions/AnotherTypeException.cs
> +/// Another Type Exception.
Неинформативно. Что за Another Type? Почему оно бросается тогда же в целом, когда и IncorrectSizeException?

2024-11-30 21:15 UTC, yurii-litvinov commented on ParallelMultiply/ParallelMultiply/MatrixOperation.cs
> +
???

2024-11-30 21:15 UTC, yurii-litvinov commented on ParallelMultiply/ParallelMultiply/Program.cs
> +using System.Diagnostics;
Up

2024-12-03 11:34 UTC, yurii-litvinov requested changes
И всё ещё надо убрать изменения про SimpleFTP из этого пуллреквеста (ну либо переоткрыть пукллреквест уже без лишних коммитов).

2024-12-03 11:34 UTC, yurii-litvinov commented on ParallelMultiply/ParallelMultiply/Exceptions/CompatibilityException.cs
> +    /// constructer.
Это и так понятно (хотя "constructor" через "o" пишется). Есть стандартная фраза "Initializes a new instance of the <see cref="имя класса"/> class."

2024-12-03 11:34 UTC, yurii-litvinov commented on ParallelMultiply/ParallelMultiply/Exceptions/CompatibilityException.cs
> +    /// <param name="message">message.</param>
Это вообще бесполезный комментарий, но его хоть просто удалить можно

2024-12-03 11:34 UTC, yurii-litvinov commented on ParallelMultiply/ParallelMultiply/FileMatrix.cs
> +    }
```suggestion
    public int[,] GetMatrix()
        => this.matrix;
```
И как раз это лучше было свойством сделать:
```csharp
    public int[,] Matrix
        => this.matrix;
```

2024-12-03 11:34 UTC, yurii-litvinov commented on ParallelMultiply/ParallelMultiply/FileMatrix.cs
> +    private static Random random = new ();
Тут и везде поправьте, пожалуйста, все комментарии StyleCop

2024-12-03 11:34 UTC, yurii-litvinov commented on ParallelMultiply/ParallelMultiply/MatrixOperation.cs
> +    /// <param name="matrix2">Second matrix of multiplication, multiplier.</param>
??

2025-03-03 11:34 UTC, ArtyomKopan reviewed
3/4

2025-03-03 11:34 UTC, ArtyomKopan commented on ParallelMultiply/ParallelMultiply.Tests/GlobalUsings.cs
> +// Copyright (c) PlaceholderCompany. All rights reserved.
```suggestion
// Copyright (c) NematMusaev. All rights reserved.
```

2025-03-03 11:34 UTC, ArtyomKopan commented on ParallelMultiply/ParallelMultiply.Tests/ParallelMultiply.Tests.cs
> +        var checkMatrix = new int[,] { { 5, 12 }, { 1, 8 } };
тут StyleCop ругается на расстановку скобок

2025-03-03 11:34 UTC, ArtyomKopan commented on ParallelMultiply/ParallelMultiply.Tests/ParallelMultiply.Tests.cs
> +        var matrix2 = new int[,] { { 1, 2 }, { 3, 3 } };
и здесь

2025-03-03 11:34 UTC, ArtyomKopan commented on ParallelMultiply/ParallelMultiply/Exceptions/CompatibilityException.cs
> +    /// <param name="message">message.</param>
тут замечание не исправлено. Нужно либо удалить комментарий, либо написать описание исключения

2025-03-03 11:34 UTC, ArtyomKopan commented on ParallelMultiply/ParallelMultiply/Exceptions/EmptyFileException.cs
> +    /// <param name="message">message.</param>
здесь тоже неправильный комментарий

2025-03-03 11:34 UTC, ArtyomKopan commented on SimpleFTP/SimpleFTP/Client.cs
> +namespace NetWork;
а здесь не хватает лицензии

2025-03-03 11:34 UTC, ArtyomKopan commented on SimpleFTP/SimpleFTP/Client.cs
> +        return response;
StyleCop ругается, что response может быть null

2025-03-03 11:34 UTC, ArtyomKopan commented on SimpleFTP/SimpleFTP/Progra.cs
Это вообще лишний файл, его нужно удалить

2025-03-03 11:34 UTC, ArtyomKopan commented on SimpleFTP/SimpleFTP/Server.cs
> +    public Server(IPAddress ipaddress, int port)
```suggestion
    private IPAddress ipaddress;
    
    public Server(IPAddress ipaddress, int port)
```

2025-03-03 11:34 UTC, ArtyomKopan commented on SimpleFTP/SimpleFTP/Server.cs
> +                string stringcommande = await reader.ReadLineAsync();
тут StyleCop тоже ругается на null

2025-12-13 20:48 UTC, merged