Simple ftp
Azernem/Semester-3 pull request #4
Opened 2024-10-24 20:55 UTC by Azernem

2024-12-20 09:16 UTC, ArtyomKopan reviewed
Сделай так, чтобы CI собирал решение.
Тест на ListDirectory не проходится.
Пока 7/10

2024-12-20 09:16 UTC, ArtyomKopan commented on SimpleFTP/SimpleFTP/Program.cs
> +Console.WriteLine("Hello, world");
этот файл не делает ничего полезного, его нужно убрать

2024-12-20 09:16 UTC, ArtyomKopan commented on SimpleFTP/SimpleFTP/Server.cs
> +                string stringcommande = await reader.ReadLineAsync() ?? throw new NullReferenceException("stringcomand cant be null");
```suggestion
                var stringCommand = await reader.ReadLineAsync() ?? throw new NullReferenceException("stringcomand cant be null");
```
можно написать var

2024-12-20 09:16 UTC, ArtyomKopan commented on SimpleFTP/SimpleFTP/Server.cs
> +        while (true)
лучше не писать while (true), а использовать CancellationToken

2024-12-20 09:16 UTC, ArtyomKopan commented on SimpleFTP/SimpleFTP/Server.cs
> +            });
здесь нужно сделать socket.Close()

2024-12-27 14:24 UTC, yurii-litvinov requested changes

2024-12-27 14:24 UTC, yurii-litvinov commented on SimpleFTP/SimpleFTP.Tests/GlobalUsings.cs
> +global using NUnit.Framework;
Надо, чтобы собиралось без предупреждений

2024-12-27 14:24 UTC, yurii-litvinov commented on SimpleFTP/SimpleFTP.Tests/SimpleFTP.Tests.cs
> +// Copyright (c) PlaceholderCompany. All rights reserved.
```suggestion
// Copyright (c) Nemat Musaev. All rights reserved.
```

2024-12-27 14:24 UTC, yurii-litvinov commented on SimpleFTP/SimpleFTP.Tests/SimpleFTP.Tests.cs
> +    /// <returns>task.</returns>
Неинформативно

2024-12-27 14:24 UTC, yurii-litvinov commented on SimpleFTP/SimpleFTP.Tests/SimpleFTP.Tests.cs
> +    const string checker = "1 ./Fileshhh";
Отступов не хватает

2024-12-27 14:24 UTC, yurii-litvinov commented on SimpleFTP/SimpleFTP.Tests/SimpleFTP.Tests.cs
> +    using var streamclient = client.GetStream();
```suggestion
    using var streamClient = client.GetStream();
```

2024-12-27 14:24 UTC, yurii-litvinov commented on SimpleFTP/SimpleFTP.Tests/SimpleFTP.Tests.cs
> +}
А что этот тест тестирует? В нём ведь только библиотечные классы

2024-12-27 14:24 UTC, yurii-litvinov commented on SimpleFTP/SimpleFTP.Tests/SimpleFTP.Tests.cs
> +        var checker = "3 1t.txt false dir true 2t.txt false";
Тест не проходит, потому что порядок, в котором возвращаются файлы, не фиксирован. Надо было на сервере сортировать перед отправкой

2024-12-27 14:24 UTC, yurii-litvinov commented on SimpleFTP/SimpleFTP.Tests/SimpleFTP.Tests.cs
> +    }
Ещё по-хорошему должны быть тесты на Get в нормальном случае и на List в случае ошибки

2024-12-27 14:24 UTC, yurii-litvinov commented on SimpleFTP/SimpleFTP/Client.cs
> +    public async Task<string> SendAndAcceptMessage(string message)
Такая реализация не привносит какой-то существенной функциональности поверх TcpClient, следовательно не нужна. Хочется, чтобы у Client было два метода — List и Get, где List возвращал бы список пар (имя, является ли директорией), а Get принимал бы Stream и записывал туда содержимое переданного файла. Представьте себе, что этот класс будет использоваться где-то в более крупной системе (например, в клиенте с пользовательским интерфейсом), там вызывающему парсить строку бы не хотелось. Кроме того, содержимое произвольного файла вообще не обязано представляться строкой, так что Get в общем случае правильно работать не сможет.

2024-12-27 14:24 UTC, yurii-litvinov commented on SimpleFTP/SimpleFTP/Program.cs
> +Console.WriteLine("Hello, world");
Не исправлено

2024-12-27 14:24 UTC, yurii-litvinov commented on SimpleFTP/SimpleFTP/Server.cs
> +namespace NetWork;
Корневое пространство имён должно называться так же, как проект. Тем более что Network — в английском одно слово.

2024-12-27 14:24 UTC, yurii-litvinov commented on SimpleFTP/SimpleFTP/Server.cs
> +        this.Run();
Это асинхронный метод, так что надо где-то дождаться его окончания. Например, сохранить Task, который он вернул, и сделать ему await в Stop

2024-12-27 14:24 UTC, yurii-litvinov commented on SimpleFTP/SimpleFTP/Server.cs
> +            await Task.Run(async () =>
await тут не даст подсоединиться следующему клиенту, пока этот не закончит работу, что противоречит условию

2024-12-27 14:24 UTC, yurii-litvinov commented on SimpleFTP/SimpleFTP/Server.cs
> +                var stringcommand = await reader.ReadLineAsync() ?? throw new NullReferenceException("stringcomand cant be null");
```suggestion
                var stringCommand = await reader.ReadLineAsync() ?? throw new NullReferenceException("stringcomand cant be null");
```

2024-12-27 14:24 UTC, yurii-litvinov commented on SimpleFTP/SimpleFTP/Server.cs
> +                var stringcommand = await reader.ReadLineAsync() ?? throw new NullReferenceException("stringcomand cant be null");
NullReferenceException кидать вручную нельзя, оно зарезервировано для рантайма .NET

2024-12-27 14:24 UTC, yurii-litvinov commented on SimpleFTP/SimpleFTP/Server.cs
> +    private readonly CancellationTokenSource cansellToken = new ();
Это какое-то насилие над английским. cancellationToken, конечно.

2024-12-27 14:24 UTC, yurii-litvinov commented on SimpleFTP/SimpleFTP/Server.cs
> +                            throw new ArgumentException("Command must be either 1 or 2.");
Нет, это надо клиенту отправить, сервер не надо убивать

2024-12-27 14:24 UTC, yurii-litvinov commented on SimpleFTP/SimpleFTP/Server.cs
> +                    Console.WriteLine("Command must be either 1 or 2.");
Ловить исключение в том же методе, где его бросаете, бессмысленно — можно было просто заменить throw new ArgumentException на Console.WriteLine

2024-12-27 14:24 UTC, yurii-litvinov commented on SimpleFTP/SimpleFTP/Server.cs
> +    }
Используйте expression-bodied-методы

2024-12-27 14:24 UTC, yurii-litvinov commented on SimpleFTP/SimpleFTP/Server.cs
> +            if (!Directory.Exists(path))
Тут отступ лишний

2024-12-27 14:24 UTC, yurii-litvinov commented on SimpleFTP/SimpleFTP/Server.cs
> +            if (!File.Exists(path))
И тут

2024-12-27 14:24 UTC, yurii-litvinov commented on SimpleFTP/SimpleFTP/Server.cs
> +            builder.Append($"{Encoding.UTF8.GetString(info).ToString()}");
Не преобразуйте содержимое файла в строку, строки и массивы байт — это разные вещи

2025-02-12 21:01 UTC, ArtyomKopan reviewed
По коду всё вроде норм, но из пяти тестов работает только один. Нужно довести их до работоспособного состояния

2025-02-12 21:01 UTC, ArtyomKopan commented on SimpleFTP/SimpleFTP.Tests/SimpleFTP.Tests.cs
> +        /*Assert.That(client.Get(path), Is.EqualTo(checkData));*/
надо раскомментировать эту строчку

2025-10-04 11:53 UTC, merged